#!/bin/bash

N=10000
CORPUS="grammar2_corpus.txt"

echo "Generating corpus from grammar2.gr..."

python3 randsent.py -n "$N" -g grammar2.gr \
| grep -v '\.\.\.' \
> "$CORPUS"

echo "Corpus generated."
echo

score() {
    GRAMMAR="$1"

    OUTPUT=$(./parse -P -g "$GRAMMAR" < "$CORPUS")

    # Show parser errors/warnings if there are any
    echo "$OUTPUT" >&2

    # Extract the final corpus cross-entropy
    echo "$OUTPUT" \
    | grep "cross-entropy" \
    | tail -1 \
    | awk '{print $4}'
}

H2=$(score grammar2.gr)
H1=$(score grammar.gr)
H3=$(score grammar3.gr)

echo
echo "Cross-entropies on corpus generated by grammar2:"
echo "grammar2 -> grammar2: $H2 bits/word"
echo "grammar2 -> grammar:  $H1 bits/word"
echo "grammar2 -> grammar3: $H3 bits/word"

echo
awk -v h2="$H2" -v h1="$H1" -v h3="$H3" '
BEGIN {
    printf "grammar is %.3f bits/word worse than grammar2\n", h1-h2
    printf "grammar3 is %.3f bits/word worse than grammar2\n", h3-h2
}'